version: '3.8'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        ports:
            - "80:80"
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
